# Generated by Django 5.0.6 on 2024-06-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position_applied', models.CharField(max_length=255)),
                ('skills', models.TextField(blank=True, null=True)),
                ('employment_type', models.CharField(max_length=100)),
            ],
        ),
    ]
