# Generated by Django 5.0.6 on 2024-07-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_candidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
